name: Release
on:
  push:
    branches:
      - master
jobs:
  maybe-release:
    name: release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: master
          release-type: node
          monorepo-tags: true
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"revert","hidden":true}]'

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.releases_created }}

      - run: corepack enable
        if: ${{ steps.release.outputs.releases_created }}

      - name: Get yarn cache directory path
        if: ${{ steps.release.outputs.releases_created }}
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Yarn cache
        if: ${{ steps.release.outputs.releases_created }}
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache

      - run: yarn install --immutable
        if: ${{ steps.release.outputs.releases_created }}

      - run: yarn build
        if: ${{ steps.release.outputs.releases_created }}

      - env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml
          
      - run: yarn workspaces foreach -v --exclude root --no-private npm publish --tolerate-republish --access public
        if: ${{ steps.release.outputs.releases_created }}
