name: "Semantic PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: semantic-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore
            revert
            docs
            refactor
            test
            perf
